### ISSUE TITLE
[Insight] Sensitive data should not be present in non-parameter configuration files - in app/config/security.yml, line 19

### ISSUE THREAD

**Issue by Lowkey2224** [Lowkey2224/tuo-result-page#44]
**[in app/config/security.yml, line 19](https://github.com/Lowkey2224/tuo-result-page/blob/3a5d440f88658f51237f74f274856435a56afdde/app/config/security.yml#L19)**

> A sensitive data has been detected in your configuration file (`password` parameter). You should consider storing it in a single parameter file.

```
            id: fos_user.user_provider.username
        in_memory:
            memory:
                users:
                    cns:
                        password: $2y$12$Pk7Hcx21hzd6VzF5gOE3LeV2yekW6EwoGCyCjcJDD8SZBZalpBq/O
                        roles: ['ROLE_USER', 'ROLE_CNS']
                    ctp:
                        password: $2y$12$ZV1SF3PtdLPAtHB4NrLLeulx3T5CY2hfsl.OJVuREjt8R9YC2vocm
                        roles: ['ROLE_USER', 'ROLE_CTP']
                    officer:
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/89a3a6d0-27b9-4d9b-b801-5e854af0b1f7/analyses/1)_
